openapi: 3.0.0
info:
  title: Laravel API
  description: API em Laravel para demonstrar conhecimentos no framework.
  version: "1.0.0"
servers:
  - url: http://localhost:8000/api
    description: Servidor de Desenvolvimento

paths:
  /register:
    post:
      summary: Registra um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - name
                - email
                - password
      responses:
        "201":
          description: Usuário registrado com sucesso
        "400":
          description: Erro de validação

  /login:
    post:
      summary: Autentica um usuário e retorna um token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        "200":
          description: Login bem-sucedido
        "401":
          description: Não autorizado

  /pipelines:
    get:
      summary: Retorna todos os pipelines
      responses:
        "200":
          description: Lista de pipelines
    post:
      summary: Cria um novo pipeline
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        "201":
          description: Pipeline criado com sucesso

  /pipelines/{id}:
    get:
      summary: Retorna um pipeline específico pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Detalhes do pipeline
    put:
      summary: Atualiza um pipeline específico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        "200":
          description: Pipeline atualizado com sucesso
    delete:
      summary: Deleta um pipeline
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Pipeline deletado com sucesso

  /cards:
    get:
      summary: Retorna todos os cards
      responses:
        "200":
          description: Lista de cards
                
    post:
      summary: Cria um novo card
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
              required:
                - name
        
      responses:
        "201":
          description: Card criado com sucesso

  /cards/{id}:
    get:
      summary: Retorna um card específico pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Detalhes do card
    put:
      summary: Atualiza um card específico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
              required:
                - name
      responses:
        "200":
          description: Card atualizado com sucesso
    delete:
      summary: Deleta um card
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Card deletado com sucesso

  /cards/{id}/move:
    post:
      summary: Move um card para o próximo pipeline
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Card movido com sucesso
        "400":
          description: Não é possível mover o card para o pipeline especificado
